[build]
  command = "npm run build -- --configuration production"
  publish = "dist/weather-app/browser"
  
[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "11.6.2"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
