[build]
  command = "npm run build -- --configuration production"
  publish = "dist/weather-app/browser"
  
[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "11.6.2"

# Desactivar el plugin autom√°tico de Angular
[[plugins]]
  package = "@netlify/angular-runtime"
  [plugins.inputs]
    disabled = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
